#!/usr/bin/env python3
"""Copy the API values from database/connection.txt into web/.env.local.

Two files need the same two values -- the database side reads connection.txt,
the Vite build reads web/.env.local -- and keeping them in step by hand is how
they drift. Edit connection.txt, run this, done.

    python database/scripts/write_web_env.py
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CONFIG = os.path.join(ROOT, 'database', 'connection.txt')
OUT = os.path.join(ROOT, 'web', '.env.local')


def read_config(path):
    if not os.path.exists(path):
        sys.exit(f'ERROR: {path} does not exist. Fill it in first.')
    cfg = {}
    for line in open(path, encoding='utf-8'):
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k, v = line.split('=', 1)
        cfg[k.strip()] = v.strip()
    return cfg


def main():
    cfg = read_config(CONFIG)
    url = cfg.get('SUPABASE_URL', '')
    key = cfg.get('SUPABASE_ANON_KEY', '')

    missing = [n for n, v in (('SUPABASE_URL', url), ('SUPABASE_ANON_KEY', key))
               if not v or '<' in v]
    if missing:
        sys.exit('ERROR: still a placeholder in database/connection.txt: '
                 + ', '.join(missing))

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('# Generated by database/scripts/write_web_env.py.\n'
                '# Edit database/connection.txt and re-run it, not this file.\n'
                f'VITE_SUPABASE_URL={url}\n'
                f'VITE_SUPABASE_ANON_KEY={key}\n')

    print(f'wrote {OUT}')
    print()
    print('Local development:  npm --prefix web run dev')
    print()
    print('For the GitHub Pages build, put the same two values in')
    print('  GitHub -> repo -> Settings -> Secrets and variables -> Actions -> Variables')
    print('  VITE_SUPABASE_URL       =', url)
    print('  VITE_SUPABASE_ANON_KEY  =', key[:24] + '...')
    return 0


if __name__ == '__main__':
    sys.exit(main())
